/** All user-visible copy for the Resources module. */
export const RESOURCES_LABELS = {
  API: {
    SUGGEST_SUCCESS: "Team suggestion ready.",
    SUGGEST_ERROR: "Failed to generate team suggestion.",
    SAVE_TEAM_SUCCESS: "Team saved.",
    SAVE_TEAM_ERROR: "Failed to save the team.",
    ADD_MEMBER_SUCCESS: "Member added to the team.",
    ADD_MEMBER_ERROR: "Failed to add the member.",
    UPDATE_MEMBER_SUCCESS: "Member updated.",
    UPDATE_MEMBER_ERROR: "Failed to update the member.",
    REMOVE_MEMBER_SUCCESS: "Member removed from the team.",
    REMOVE_MEMBER_ERROR: "Failed to remove the member.",
    CLEAR_TEAM_SUCCESS: "Team cleared.",
    CLEAR_TEAM_ERROR: "Failed to clear the team.",
  },
  STATE: {
    ERROR_TITLE: "Couldn't load resources",
    ERROR_BODY:
      "Something went wrong while loading team resources. Please try again.",
    EMPTY_TITLE: "No team members yet",
    EMPTY_BODY: "There are no resources allocated to this project yet.",
  },
  STATUS: {
    OVERLOADED: "Overloaded",
    NEAR_CAPACITY: "Near capacity",
    AVAILABLE: "Available",
    BLOCKED: "Blocked",
  },
  TEAM_MEMBERS: {
    TITLE: "Team Members",
    AI_SUGGEST: "AI Suggest Team →",
    SYNC_SIMEIP: "Sync from SimERP",
    SYNCING: "Syncing…",
    COLUMN_NAME: "Name",
    COLUMN_ROLE: "Role",
    COLUMN_SKILLS: "Skills",
    COLUMN_RATE: "Rate/Day",
    COLUMN_UTILIZATION: "Utilization",
    COLUMN_STATUS: "Status",
    COLUMN_ACTIONS: "Actions",
    REMOVE: "Remove member",
    EMPTY: "No team members yet. Use AI Suggest Team to build one.",
  },
  HEATMAP: {
    TITLE: "Cross-Sprint Utilization Heatmap",
    LEGEND: "Green <80% · Amber 80–100% · Red >100%",
    COLUMN_MEMBER: "Team Member",
    WEEK_PREFIX: "Week",
    EMPTY_CELL: "–",
    LEAVE_CELL: "Leave",
  },
  SUGGEST: {
    TITLE: "AI Team Suggestion",
    DESCRIPTION: "Recommended team composition based on the project backlog.",
    STORY_POINTS: "Total story points",
    SPRINTS: "Estimated sprints",
    COUNT_NEEDED: "Needed",
    SUGGESTED_MEMBERS: "Suggested members",
    NO_MEMBERS: "No matching members found.",
    LOADING: "Generating suggestions…",
    LOADING_BODY:
      "Analysing the backlog and matching candidates from the roster.",
    EMPTY: "No recommendations available.",
    SELECTED: "selected",
    CREATE_TEAM: "Create Team",
    CREATE_SUCCESS: "Team created.",
    MATCH: "match",
    EXPERIENCE_SUFFIX: "yrs exp",
    AVAILABILITY: "available",
    ALLOCATED: "allocated",
    SOURCE_LOCAL: "From local roster",
    ON_LEAVE: "On leave",
    NOTICE_PERIOD: "Notice period",
    CONTRACTOR: "Contractor",
    RATING_OVERALL: "Overall Rating",
    RATING_AI: "AI Rating",
    RATING_COMMUNICATION: "Communication",
    RATIONALE: "Why this match",
    SKILLS: "Skills",
  },
} as const;
