export const DASHBOARD_LABELS = {
  STATS: {
    RISK_SCORE: "Risk Score",
    RISK_SUFFIX: "/100",
    RISK_BADGE_LOW: "LOW",
    RISK_BADGE_MEDIUM: "MEDIUM",
    RISK_BADGE_HIGH: "HIGH",
    RISK_BADGE_CRITICAL: "CRITICAL",
    RISK_NOT_AVAILABLE: "—",
    COMPLETION: "Task Completion",
    COMPLETION_SUFFIX: "%",
    COMPLETION_CAPTION_TEMPLATE: "{completed}/{total} tasks",
    TOTAL_TASKS: "Total Tasks",
    TOTAL_TASKS_SUFFIX: "tasks",
    COMPLETED_TASKS: "Completed Tasks",
    COMPLETED_TASKS_SUFFIX: "tasks",
    OPEN_TASKS: "Open Tasks",
    OPEN_TASKS_SUFFIX: "tasks",
    OPEN_TASKS_ALERT_TEMPLATE: "⚠ {count} blocked",
    IN_PROGRESS_TASKS: "In Progress",
    IN_PROGRESS_TASKS_SUFFIX: "tasks",
    BLOCKED_TASKS: "Blocked Tasks",
    BLOCKED_TASKS_SUFFIX: "tasks",
    TEAM_SIZE: "Team Size",
    TEAM_SIZE_SUFFIX: "members",
  },
  BURNDOWN: {
    TITLE: "Sprint Burndown — Sprint 3",
    SUBTITLE: "Jun 10 – Jun 28, 2026",
    BADGE: "Behind",
    IDEAL: "Ideal Burndown",
    ACTUAL: "Actual Remaining",
  },
  VELOCITY: {
    TITLE: "Velocity Trend",
    SUBTITLE: "Points completed per sprint",
  },
  ACTIVITY: {
    TITLE: "Recent Activity",
  },
  MILESTONES: {
    TITLE: "Milestones",
  },
} as const;
