/** All user-visible copy for the Projects module. */
export const PROJECTS_LABELS = {
  API: {
    CREATE_SUCCESS: "Project created successfully.",
    CREATE_ERROR: "Failed to create project.",
    UPDATE_SUCCESS: "Project updated successfully.",
    UPDATE_ERROR: "Failed to update project.",
  },
  LIST: {
    PAGE_TITLE: "Projects",
    PAGE_SUBTITLE: "All projects across your organization.",
    LOAD_ERROR: "Failed to load projects.",
    EMPTY_TITLE: "No projects yet",
    EMPTY_DESCRIPTION: "Get started by creating your first project.",
    CREATE_BUTTON: "Create Project",
  },
  TABLE: {
    COLUMN_NAME: "Name",
    COLUMN_STATUS: "Status",
    COLUMN_CLIENT: "Client",
    COLUMN_START_DATE: "Start Date",
    COLUMN_TARGET_END_DATE: "Target End Date",
    COLUMN_BUDGET: "Budget",
    COLUMN_CREATED_AT: "Created",
    COLUMN_ACTIONS: "Actions",
    EDIT_ACTION_LABEL: "Edit project",
  },
  DIALOG: {
    CREATE_TITLE: "Create Project",
    CREATE_DESCRIPTION: "Add a new project to your organization.",
    SUBMIT_BUTTON: "Create Project",
    EDIT_TITLE: "Edit Project",
    EDIT_DESCRIPTION: "Update this project's details.",
    SAVE_BUTTON: "Save Changes",
    CANCEL_BUTTON: "Cancel",
  },
  FORM: {
    NAME_LABEL: "Name",
    NAME_PLACEHOLDER: "e.g. TechFlow Logistics",
    NAME_REQUIRED: "Project name is required.",
    DESCRIPTION_LABEL: "Description",
    DESCRIPTION_PLACEHOLDER: "Brief description of the project",
    CLIENT_NAME_LABEL: "Client Name",
    CLIENT_NAME_PLACEHOLDER: "e.g. Acme Corp",
    STATUS_LABEL: "Status",
    STATUS_PLACEHOLDER: "e.g. active",
    START_DATE_LABEL: "Start Date",
    TARGET_END_DATE_LABEL: "Target End Date",
    DATE_PICK_PLACEHOLDER: "Pick a date",
    BUDGET_LABEL: "Budget (USD)",
    BUDGET_PLACEHOLDER: "e.g. 50000",
    BUDGET_INVALID: "Budget must be a positive number.",
    DATE_RANGE_INVALID: "Target end date must be on or after the start date.",
  },
} as const;
